### ISSUE TITLE
Bug File Not Found Mimetype Directory

### ISSUE THREAD

**Issue by jamesmartins** [JSpiner/epub-viewer#34]
Please, I need your help in this awesome epub library.
The project runs successfully on my Android Studio 3.1.2.
But, I get this single error:

`Caused by: java.io.FileNotFoundException: /data/user/0/net.jspiner.epub_viewer/cache/beyond_good_and_evil.epub/mimetype (Not a directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:308)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
        at net.jspiner.epubstream.EpubStream.extractFile(EpubStream.kt:64)
        at net.jspiner.epubstream.EpubStream.access$extractFile(EpubStream.kt:22)
        at net.jspiner.epubstream.EpubStream$unzip$1.subscribe(EpubStream.kt:49)
       ...`

**Comment by JSpiner** [comment]
hi!
can you give me more information about your situation?

**Comment by JSpiner** [comment]
It seems that unzip logic is not working.
Did you check WRITE-FILE permission?
